[package]
name = "some_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = {version = "1.0.103", features = ["proc-macro"]}
quote = "1.0.41"
syn = {version = "2.0.108", features = ["extra-traits", "full", "printing"]}
