[package]
name = "cabriolet_examples"
version = "0.1.0"
edition = "2024"

[dependencies]
some_macros = { path = "../cabriolet_library/some_macros" }
secrets_structs = { path = "../cabriolet_library/secrets_structs" }
async-runtime = { path = "../async-runtime" }
futures = "0.3.31"
